"""Unified Platform Owner Control Tower for Scout, warehouse, and AI operations."""
from flask import Blueprint, g, jsonify, redirect, render_template_string, session

PAGE = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Scout Control Tower · BrokerBeacon AI</title><style>
:root{--bg:#07162e;--panel:#102547;--line:#ffffff1f;--text:#f7fbff;--muted:#a7b7cf;--blue:#58a6ff;--green:#4bd19b;--red:#ff7d93}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#07162e,#0b2145);color:var(--text);font:14px Inter,Segoe UI,Arial,sans-serif}main{max-width:1420px;margin:auto;padding:26px}.top,.head{display:flex;justify-content:space-between;gap:16px;align-items:center}.top a{color:#bfe0ff;text-decoration:none}h1,h2,h3{margin:6px 0}.muted{color:var(--muted);line-height:1.55}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tabs button,input,select{padding:10px 12px;border-radius:9px;border:1px solid var(--line);background:#081b38;color:white}.tabs button{cursor:pointer}.tabs button.active,.primary{background:#236ac9}.tab{display:none}.tab.active{display:block}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0}.card,.panel{background:#102547e8;border:1px solid var(--line);border-radius:16px;padding:18px}.card strong{display:block;font-size:28px;margin-top:7px}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}input{flex:1;min-width:150px}button{padding:10px 12px;border-radius:9px;border:1px solid var(--line);background:#081b38;color:white;cursor:pointer}.danger{background:#70243a}.good{color:var(--green)}.bad{color:var(--red)}.pill{display:inline-block;padding:5px 8px;border-radius:999px;background:#58a6ff1f;color:#bfe0ff;font-size:11px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:10px;text-transform:uppercase;color:var(--muted)}.state-row{display:grid;grid-template-columns:44px 1fr 70px 70px;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid var(--line)}.bar{height:7px;background:#ffffff14;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--green))}.empty{padding:25px;text-align:center;color:var(--muted)}.error{background:#70243a;padding:10px;border-radius:9px;margin:10px 0;display:none}.brief{font-size:16px;line-height:1.65}.agent{border-left:3px solid var(--blue);padding-left:12px;margin:12px 0}@media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.top,.head{align-items:flex-start;flex-direction:column}}
</style></head><body><main>
<div class="top"><div><div class="pill">PLATFORM OWNER · UNIFIED CONTROL TOWER</div><h1>Scout Control Tower</h1><p class="muted">One command center for discovery, the national warehouse, AI agents, bounded autonomy, and system health.</p></div><a href="/">← Back to BrokerBeacon</a></div><div id="error" class="error"></div>
<div class="tabs"><button class="active" data-tab="briefing">Executive Briefing</button><button data-tab="operations">Discovery</button><button data-tab="warehouse">Warehouse</button><button data-tab="ai">AI Team</button><button data-tab="autonomy">Autonomy</button><button data-tab="imports">Imports & Health</button></div>
<section id="briefing" class="tab active"><div class="grid"><div class="panel"><h2>Morning briefing from Ash</h2><div id="briefingText" class="brief empty">Loading executive briefing…</div></div><div class="panel"><h2>Recommended focus</h2><div id="focus" class="muted">Loading…</div><button class="primary" style="margin-top:14px" onclick="runCycle()">Run one guarded growth cycle</button></div></div><div class="cards"><div class="card"><span class="muted">Warehouse companies</span><strong id="briefCompanies">0</strong></div><div class="card"><span class="muted">Discovered contacts</span><strong id="briefContacts">0</strong></div><div class="card"><span class="muted">Pending review</span><strong id="briefPending">0</strong></div><div class="card"><span class="muted">High opportunity</span><strong id="briefHigh">0</strong></div><div class="card"><span class="muted">Pending duplicates</span><strong id="briefDupes">0</strong></div></div></section>
<section id="operations" class="tab"><div class="cards"><div class="card"><span class="muted">Emergency stop</span><strong id="emergency">—</strong></div><div class="card"><span class="muted">Pilot state</span><strong id="pilot">—</strong></div><div class="card"><span class="muted">Daily budget</span><strong id="budget">—</strong></div><div class="card"><span class="muted">Discoveries</span><strong id="discoveries">0</strong></div><div class="card"><span class="muted">Configured providers</span><strong id="providers">0</strong></div></div><div class="grid"><div class="panel"><h2>Scout status</h2><div id="operationsDetail" class="empty">Loading…</div></div><div class="panel"><h2>Provider yield</h2><div id="providerBoard" class="empty">No provider runs yet.</div></div></div></section>
<section id="warehouse" class="tab"><div class="cards"><div class="card"><span class="muted">Companies</span><strong id="companies">0</strong></div><div class="card"><span class="muted">Loan officers</span><strong id="officers">0</strong></div><div class="card"><span class="muted">Branches</span><strong id="branches">0</strong></div><div class="card"><span class="muted">Licenses</span><strong id="licenses">0</strong></div><div class="card"><span class="muted">Duplicate review</span><strong id="duplicates">0</strong></div></div><div class="grid"><div class="panel"><h2>Warehouse search</h2><div class="filters"><input id="q" placeholder="Company, loan officer, or NMLS"><input id="state" maxlength="2" style="flex:0 0 90px" placeholder="State"><button class="primary" onclick="runSearch()">Search</button></div><div id="results" class="empty">Enter a name, state, or NMLS ID.</div></div><div class="panel"><h2>Coverage by state</h2><div id="coverage" class="empty">No warehouse coverage yet.</div></div></div></section>
<section id="ai" class="tab"><div class="grid"><div class="panel"><h2>AI organization</h2><div id="agents" class="empty">Loading agents…</div></div><div class="panel"><h2>Growth mission</h2><div id="mission" class="muted">Loading…</div><h3 style="margin-top:18px">Strategy leaderboard</h3><div id="strategies" class="empty">No strategy outcomes yet.</div></div></div></section>
<section id="autonomy" class="tab"><div class="grid"><div class="panel"><h2>Bounded autonomy</h2><div class="filters"><label><input id="autoEnabled" type="checkbox" style="min-width:auto"> Enabled</label><input id="approvedStates" placeholder="Approved states: CA,TX,FL"><input id="dailyCost" type="number" min="0" placeholder="Daily budget cents"><button class="primary" onclick="savePolicy()">Save guardrails</button></div><div id="policy" class="muted">Loading policy…</div></div><div class="panel"><h2>Next planned cycle</h2><div id="plan" class="empty">Loading plan…</div></div></div><div class="panel" style="margin-top:14px"><h2>Recent autonomous runs</h2><div id="runs" class="empty">No autonomous runs yet.</div></div></section>
<section id="imports" class="tab"><div class="grid"><div class="panel"><h2>Import jobs</h2><div id="jobs" class="empty">No import jobs yet.</div></div><div class="panel"><h2>Enrichment & worker health</h2><div id="enrichment" class="empty">Loading…</div></div></div></section>
</main><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(url,opt){let r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...(opt||{})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}function fail(e){let x=document.getElementById('error');x.textContent=e.message||e;x.style.display='block'}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
async function loadAll(){await Promise.allSettled([loadOperations(),loadWarehouse(),loadAiOps(),loadDiscoveryOps()])}
async function loadOperations(){try{let d=await api('/api/scout-control-tower');emergency.textContent=d.settings?.emergency_stop?'STOPPED':'Ready';pilot.textContent=d.settings?.pilot_state||'—';budget.textContent=d.settings?.daily_cost_limit_cents!=null?'$'+(d.settings.daily_cost_limit_cents/100).toFixed(2):'—';discoveries.textContent=(d.summary?.discovery_count||d.discovery_count||0).toLocaleString();operationsDetail.innerHTML=`<table><tbody><tr><th>Autopilot</th><td>${esc(d.autopilot?.enabled?'Enabled':'Paused')}</td></tr><tr><th>Last run</th><td>${esc(d.autopilot?.last_run_at||d.last_run_at||'Not run')}</td></tr><tr><th>Next run</th><td>${esc(d.autopilot?.next_run_at||d.next_run_at||'Not scheduled')}</td></tr></tbody></table>`}catch(e){fail(e)}}
async function loadDiscoveryOps(){try{let d=await api('/api/platform/discovery-ops');providers.textContent=(d.configured_providers||[]).length;providerBoard.innerHTML=(d.provider_leaderboard||[]).length?`<table><thead><tr><th>Provider</th><th>Unique</th><th>Runs</th><th>Failures</th></tr></thead><tbody>${d.provider_leaderboard.map(x=>`<tr><td>${esc(x.provider)}</td><td>${x.unique_results||0}</td><td>${x.runs||0}</td><td>${x.failures||0}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No provider runs yet.</div>';let e=d.enrichment||{};enrichment.innerHTML=`<table><tbody><tr><th>Contacts found</th><td>${e.contacts||0}</td></tr><tr><th>Domains processed</th><td>${e.domains||0}</td></tr><tr><th>With email</th><td>${e.with_email||0}</td></tr><tr><th>With phone</th><td>${e.with_phone||0}</td></tr><tr><th>Queue</th><td>${esc(JSON.stringify(e.queue||{}))}</td></tr></tbody></table>`}catch(e){fail(e)}}
async function loadAiOps(){try{let d=await api('/api/platform/ai-ops'),b=d.briefing||{},a=d.autonomy||{},g=d.growth||{};briefCompanies.textContent=b.warehouse_companies||0;briefContacts.textContent=b.discovered_contacts||0;briefPending.textContent=b.pending_review||0;briefHigh.textContent=b.high_opportunity||0;briefDupes.textContent=b.pending_duplicates||0;briefingText.innerHTML=`<b>${esc(b.headline||'AI team ready')}</b><br>Scout is expanding coverage, Atlas is protecting data quality, Signal is prioritizing opportunity, Coach is preparing action, and Ash is coordinating the mission.`;focus.textContent=b.recommended_focus||'Review the highest-value pending prospects.';agents.innerHTML=(d.agents?.agents||[]).map(x=>`<div class="agent"><b>${esc(x.display_name)}</b> · ${esc(x.role)}<br><span class="muted">${esc(x.personality)} · v${x.version}</span></div>`).join('');mission.textContent=g.mission?.mission||'';strategies.innerHTML=(g.strategies||[]).length?`<table><thead><tr><th>Agent</th><th>Strategy</th><th>Trials</th><th>Reward</th></tr></thead><tbody>${g.strategies.slice(0,12).map(x=>`<tr><td>${esc(x.agent_key)}</td><td>${esc(x.strategy_key)}</td><td>${x.trials}</td><td>${x.average_reward}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Strategies are initialized and will learn from outcomes.</div>';let p=a.policy||{};autoEnabled.checked=!!p.enabled;approvedStates.value=(p.approved_states||[]).join(',');dailyCost.value=p.max_daily_cost_cents??1000;policy.textContent=`Human review: ${p.require_human_review?'required':'optional'} · CRM promotion: ${p.allow_crm_promotion?'allowed':'blocked'} · Outreach: ${p.allow_outreach?'allowed':'blocked'}`;plan.innerHTML=`<b>${esc(a.plan?.status||'Unknown')}</b><br>${esc(a.plan?.reason||('Next state: '+(a.plan?.state||'—')))}<br><span class="muted">${esc(JSON.stringify(a.plan?.actions||[]))}</span>`;runs.innerHTML=(a.recent_runs||[]).length?`<table><thead><tr><th>Run</th><th>State</th><th>Status</th><th>Contacts</th><th>AI processed</th><th>Cost</th></tr></thead><tbody>${a.recent_runs.map(x=>`<tr><td>#${x.id}</td><td>${esc(x.state||'—')}</td><td>${esc(x.status)}</td><td>${x.contacts_found}</td><td>${x.ai_processed}</td><td>$${((x.estimated_cost_cents||0)/100).toFixed(2)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No autonomous runs yet.</div>'}catch(e){fail(e)}}
async function savePolicy(){try{let body={enabled:autoEnabled.checked,approved_states:approvedStates.value.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),max_daily_cost_cents:Number(dailyCost.value||0)};await api('/api/platform/ai-ops/policy',{method:'POST',body:JSON.stringify(body)});await loadAiOps()}catch(e){fail(e)}}async function runCycle(){try{await api('/api/platform/ai-ops/run-cycle',{method:'POST',body:'{}'});await loadAll()}catch(e){fail(e)}}
async function loadWarehouse(){try{let d=await api('/api/platform/warehouse');for(let k of ['companies','officers','branches','licenses'])document.getElementById(k).textContent=(d[k]||0).toLocaleString();duplicates.textContent=(d.pending_duplicates||0).toLocaleString();let max=Math.max(1,...d.coverage.map(x=>x.companies));coverage.innerHTML=d.coverage.length?d.coverage.map(x=>`<div class="state-row"><b>${esc(x.state||'—')}</b><div class="bar"><i style="width:${Math.max(3,x.companies/max*100)}%"></i></div><span>${x.companies} firms</span><span>${x.officers} LOs</span></div>`).join(''):'<div class="empty">No warehouse coverage yet.</div>';jobs.innerHTML=d.recent_jobs.length?`<table><thead><tr><th>Job</th><th>State</th><th>Status</th><th>Received</th><th>Created</th><th>Updated</th><th>Rejected</th></tr></thead><tbody>${d.recent_jobs.map(x=>`<tr><td>#${x.id}</td><td>${esc(x.state||'All')}</td><td>${esc(x.status)}</td><td>${x.records_received}</td><td>${x.companies_created}</td><td>${x.companies_updated}</td><td>${x.rejected_records}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No import jobs yet.</div>'}catch(e){fail(e)}}
async function runSearch(){try{let d=await api('/api/platform/warehouse/search?q='+encodeURIComponent(q.value)+'&state='+encodeURIComponent(state.value.toUpperCase()));let rows=[...d.companies.map(x=>({type:'Company',name:x.legal_name,nmls:x.nmls_id,location:[x.city,x.state].filter(Boolean).join(', '),contact:x.public_email||x.phone||'',status:x.verification_status})),...d.officers.map(x=>({type:'Loan officer',name:x.full_name,nmls:x.nmls_id,location:[x.city,x.state].filter(Boolean).join(', '),contact:x.public_email||x.phone||'',status:x.company}))];results.innerHTML=rows.length?`<table><thead><tr><th>Type</th><th>Name</th><th>NMLS</th><th>Location</th><th>Contact</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.type)}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.nmls||'—')}</td><td>${esc(x.location||'—')}</td><td>${esc(x.contact||'—')}</td><td>${esc(x.status||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No matching records.</div>'}catch(e){fail(e)}}
loadAll();</script></body></html>'''


def _is_platform_owner():
    for user in (getattr(g, "saas_user", None), getattr(g, "current_user", None), getattr(g, "user", None)):
        if user is None:
            continue
        try:
            if bool(user["is_platform_owner"]):
                return True
        except (KeyError, TypeError):
            if bool(getattr(user, "is_platform_owner", 0)):
                return True
    return bool(session.get("is_platform_owner"))


def install_national_data_center(app):
    bp = Blueprint("national_data_center", __name__)

    @bp.get("/platform/control-tower")
    def control_tower_page():
        if not _is_platform_owner():
            return jsonify(error="Platform owner access required"), 403
        return render_template_string(PAGE)

    @bp.get("/platform/data-center")
    def legacy_data_center_page():
        return redirect("/platform/control-tower", code=302)

    app.register_blueprint(bp)
    return bp
