"""Platform-owner National Data Center UI for Sprint 37."""
from flask import Blueprint, render_template_string

PAGE = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>National Data Center · BrokerBeacon AI</title><style>
:root{--bg:#07162e;--panel:#102547;--line:#ffffff1f;--text:#f7fbff;--muted:#a7b7cf;--blue:#58a6ff;--green:#4bd19b}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#07162e,#0b2145);color:var(--text);font:14px Inter,Segoe UI,Arial,sans-serif}
main{max-width:1320px;margin:auto;padding:28px}.top,.head{display:flex;justify-content:space-between;gap:16px;align-items:center}.top a{color:#bfe0ff;text-decoration:none}
h1{margin:6px 0}.muted{color:var(--muted);line-height:1.55}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:20px 0}.card,.panel{background:#102547e8;border:1px solid var(--line);border-radius:16px;padding:18px}.card strong{display:block;font-size:30px;margin-top:7px}.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:14px}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}input,select,button{padding:10px 12px;border-radius:9px;border:1px solid var(--line);background:#081b38;color:white}input{flex:1;min-width:210px}button{cursor:pointer}.primary{background:#236ac9;border-color:#438ae5}.pill{display:inline-block;padding:5px 8px;border-radius:999px;background:#58a6ff1f;color:#bfe0ff;font-size:11px}table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid var(--line);text-align:left}th{font-size:10px;text-transform:uppercase;color:var(--muted)}.state-row{display:grid;grid-template-columns:44px 1fr 70px 70px;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid var(--line)}.bar{height:7px;background:#ffffff14;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--green))}.empty{padding:28px;text-align:center;color:var(--muted)}.error{background:#70243a;padding:10px;border-radius:9px;margin:10px 0;display:none}@media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.top,.head{align-items:flex-start;flex-direction:column}}</style></head>
<body><main><div class="top"><div><div class="pill">PLATFORM OWNER · SPRINT 37</div><h1>National Prospect Data Center</h1><p class="muted">Manage the nationwide discovery warehouse separately from active CRM relationships. Imported records remain review-gated and never enter outreach automatically.</p></div><a href="/">← Back to BrokerBeacon</a></div>
<div id="error" class="error"></div><section class="cards"><div class="card"><span class="muted">Companies</span><strong id="companies">0</strong></div><div class="card"><span class="muted">Loan officers</span><strong id="officers">0</strong></div><div class="card"><span class="muted">Branches</span><strong id="branches">0</strong></div><div class="card"><span class="muted">Licenses</span><strong id="licenses">0</strong></div><div class="card"><span class="muted">Duplicate review</span><strong id="duplicates">0</strong></div></section>
<section class="grid"><div class="panel"><div class="head"><div><h2>Warehouse search</h2><p class="muted">Search company and officer names, NMLS IDs, and state coverage.</p></div><button onclick="loadDashboard()">Refresh</button></div><div class="filters"><input id="q" placeholder="Company, loan officer, or NMLS"><input id="state" maxlength="2" style="flex:0 0 90px" placeholder="State"><button class="primary" onclick="runSearch()">Search</button></div><div id="results" class="empty">Enter a name, state, or NMLS ID to search the national warehouse.</div></div>
<div class="panel"><h2>Coverage by state</h2><div id="coverage" class="empty">No warehouse coverage yet.</div></div></section>
<section class="panel" style="margin-top:14px"><div class="head"><div><h2>Recent import jobs</h2><p class="muted">Imports must identify an authorized, public, or licensed source before records are accepted.</p></div><span class="pill">Review-gated</span></div><div id="jobs" class="empty">No import jobs yet.</div></section></main>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url){let r=await fetch(url,{credentials:'same-origin'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function fail(e){let x=document.getElementById('error');x.textContent=e.message||e;x.style.display='block'}
async function loadDashboard(){try{let d=await api('/api/platform/warehouse');for(let k of ['companies','officers','branches','licenses'])document.getElementById(k).textContent=(d[k]||0).toLocaleString();document.getElementById('duplicates').textContent=(d.pending_duplicates||0).toLocaleString();let max=Math.max(1,...d.coverage.map(x=>x.companies));document.getElementById('coverage').innerHTML=d.coverage.length?d.coverage.map(x=>`<div class="state-row"><b>${esc(x.state||'—')}</b><div class="bar"><i style="width:${Math.max(3,x.companies/max*100)}%"></i></div><span>${x.companies} firms</span><span>${x.officers} LOs</span></div>`).join(''):'<div class="empty">No warehouse coverage yet. Register a source and run the first approved import.</div>';document.getElementById('jobs').innerHTML=d.recent_jobs.length?`<table><thead><tr><th>Job</th><th>State</th><th>Status</th><th>Received</th><th>Created</th><th>Updated</th><th>Rejected</th></tr></thead><tbody>${d.recent_jobs.map(x=>`<tr><td>#${x.id}</td><td>${esc(x.state||'All')}</td><td><span class="pill">${esc(x.status)}</span></td><td>${x.records_received}</td><td>${x.companies_created}</td><td>${x.companies_updated}</td><td>${x.rejected_records}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No import jobs yet.</div>'}catch(e){fail(e)}}
async function runSearch(){try{let q=document.getElementById('q').value,state=document.getElementById('state').value.toUpperCase();let d=await api('/api/platform/warehouse/search?q='+encodeURIComponent(q)+'&state='+encodeURIComponent(state));let rows=[...d.companies.map(x=>({type:'Company',name:x.legal_name,nmls:x.nmls_id,location:[x.city,x.state].filter(Boolean).join(', '),contact:x.public_email||x.phone||'',status:x.verification_status})),...d.officers.map(x=>({type:'Loan officer',name:x.full_name,nmls:x.nmls_id,location:[x.city,x.state].filter(Boolean).join(', '),contact:x.public_email||x.phone||'',status:x.company}))];document.getElementById('results').innerHTML=rows.length?`<table><thead><tr><th>Type</th><th>Name</th><th>NMLS</th><th>Location</th><th>Public contact</th><th>Status / company</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.type)}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.nmls||'—')}</td><td>${esc(x.location||'—')}</td><td>${esc(x.contact||'—')}</td><td>${esc(x.status||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No matching warehouse records.</div>'}catch(e){fail(e)}}
document.getElementById('q').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});document.getElementById('state').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});loadDashboard();
</script></body></html>'''


def install_national_data_center(app):
    bp = Blueprint("national_data_center", __name__)

    @bp.get("/platform/data-center")
    def national_data_center_page():
        return render_template_string(PAGE)

    app.register_blueprint(bp)
    return bp
