"""Unified Platform Owner Control Tower for Scout and the Sprint 37 warehouse."""
from flask import Blueprint, g, jsonify, redirect, render_template_string, session

PAGE = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Scout Control Tower · BrokerBeacon AI</title><style>
:root{--bg:#07162e;--panel:#102547;--line:#ffffff1f;--text:#f7fbff;--muted:#a7b7cf;--blue:#58a6ff;--green:#4bd19b;--red:#ff7d93}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#07162e,#0b2145);color:var(--text);font:14px Inter,Segoe UI,Arial,sans-serif}main{max-width:1380px;margin:auto;padding:28px}.top,.head{display:flex;justify-content:space-between;gap:16px;align-items:center}.top a{color:#bfe0ff;text-decoration:none}h1{margin:6px 0}.muted{color:var(--muted);line-height:1.55}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tabs button{padding:10px 14px;border-radius:9px;border:1px solid var(--line);background:#081b38;color:white;cursor:pointer}.tabs button.active{background:#236ac9}.tab{display:none}.tab.active{display:block}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0}.card,.panel{background:#102547e8;border:1px solid var(--line);border-radius:16px;padding:18px}.card strong{display:block;font-size:30px;margin-top:7px}.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:14px}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}input,button{padding:10px 12px;border-radius:9px;border:1px solid var(--line);background:#081b38;color:white}input{flex:1;min-width:210px}button{cursor:pointer}.primary{background:#236ac9;border-color:#438ae5}.danger{background:#70243a}.pill{display:inline-block;padding:5px 8px;border-radius:999px;background:#58a6ff1f;color:#bfe0ff;font-size:11px}table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid var(--line);text-align:left}th{font-size:10px;text-transform:uppercase;color:var(--muted)}.state-row{display:grid;grid-template-columns:44px 1fr 70px 70px;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid var(--line)}.bar{height:7px;background:#ffffff14;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--green))}.empty{padding:28px;text-align:center;color:var(--muted)}.error{background:#70243a;padding:10px;border-radius:9px;margin:10px 0;display:none}@media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.top,.head{align-items:flex-start;flex-direction:column}}</style></head>
<body><main><div class="top"><div><div class="pill">PLATFORM OWNER · UNIFIED CONTROL TOWER</div><h1>Scout Control Tower</h1><p class="muted">One workspace for discovery operations, nationwide warehouse coverage, import health, and duplicate review. Imported records remain separate from active CRM prospects until explicitly approved.</p></div><a href="/">← Back to BrokerBeacon</a></div><div id="error" class="error"></div>
<div class="tabs"><button class="active" data-tab="operations">Discovery Operations</button><button data-tab="warehouse">National Warehouse</button><button data-tab="imports">Imports & Quality</button></div>
<section id="operations" class="tab active"><div class="cards"><div class="card"><span class="muted">Emergency stop</span><strong id="emergency">—</strong></div><div class="card"><span class="muted">Pilot state</span><strong id="pilot">—</strong></div><div class="card"><span class="muted">Daily budget</span><strong id="budget">—</strong></div><div class="card"><span class="muted">Discoveries</span><strong id="discoveries">0</strong></div><div class="card"><span class="muted">Duplicates</span><strong id="scoutDuplicates">0</strong></div></div><div class="grid"><div class="panel"><div class="head"><div><h2>Scout status</h2><p class="muted">Existing discovery automation and guardrails remain authoritative.</p></div><button onclick="loadOperations()">Refresh</button></div><div id="operationsDetail" class="empty">Loading Scout Control Tower…</div></div><div class="panel"><h2>Quick actions</h2><p class="muted">Use the existing Platform Admin discovery workflow to launch state searches and review candidates.</p><a class="pill" href="/#platformadmin">Open Platform Admin</a><p class="muted" style="margin-top:18px">The national warehouse extends Scout; it does not create a second discovery engine.</p></div></div></section>
<section id="warehouse" class="tab"><div class="cards"><div class="card"><span class="muted">Companies</span><strong id="companies">0</strong></div><div class="card"><span class="muted">Loan officers</span><strong id="officers">0</strong></div><div class="card"><span class="muted">Branches</span><strong id="branches">0</strong></div><div class="card"><span class="muted">Licenses</span><strong id="licenses">0</strong></div><div class="card"><span class="muted">Duplicate review</span><strong id="duplicates">0</strong></div></div><div class="grid"><div class="panel"><div class="head"><div><h2>Warehouse search</h2><p class="muted">Search broker companies, loan officers, states, and NMLS IDs.</p></div><button onclick="loadWarehouse()">Refresh</button></div><div class="filters"><input id="q" placeholder="Company, loan officer, or NMLS"><input id="state" maxlength="2" style="flex:0 0 90px" placeholder="State"><button class="primary" onclick="runSearch()">Search</button></div><div id="results" class="empty">Enter a name, state, or NMLS ID.</div></div><div class="panel"><h2>Coverage by state</h2><div id="coverage" class="empty">No warehouse coverage yet.</div></div></div></section>
<section id="imports" class="tab"><div class="panel"><div class="head"><div><h2>Import jobs and data quality</h2><p class="muted">Only documented authorized, public, or licensed sources may feed the warehouse.</p></div><span class="pill">Review-gated</span></div><div id="jobs" class="empty">No import jobs yet.</div></div></section>
</main><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(url){let r=await fetch(url,{credentials:'same-origin'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}function fail(e){let x=document.getElementById('error');x.textContent=e.message||e;x.style.display='block'}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
async function loadOperations(){try{let d=await api('/api/scout-control-tower');document.getElementById('emergency').textContent=d.settings?.emergency_stop?'STOPPED':'Ready';document.getElementById('pilot').textContent=d.settings?.pilot_state||'—';document.getElementById('budget').textContent=d.settings?.daily_cost_limit_cents!=null?'$'+(d.settings.daily_cost_limit_cents/100).toFixed(2):'—';document.getElementById('discoveries').textContent=(d.summary?.discovery_count||d.discovery_count||0).toLocaleString();document.getElementById('scoutDuplicates').textContent=(d.summary?.duplicate_count||d.duplicate_count||0).toLocaleString();document.getElementById('operationsDetail').innerHTML=`<table><tbody><tr><th>Autopilot</th><td>${esc(d.autopilot?.enabled?'Enabled':'Paused')}</td></tr><tr><th>Last run</th><td>${esc(d.autopilot?.last_run_at||d.last_run_at||'Not run')}</td></tr><tr><th>Next run</th><td>${esc(d.autopilot?.next_run_at||d.next_run_at||'Not scheduled')}</td></tr><tr><th>Query budget</th><td>${esc(d.autopilot?.daily_query_budget||d.daily_query_budget||'—')}</td></tr></tbody></table>`}catch(e){fail(e)}}
async function loadWarehouse(){try{let d=await api('/api/platform/warehouse');for(let k of ['companies','officers','branches','licenses'])document.getElementById(k).textContent=(d[k]||0).toLocaleString();document.getElementById('duplicates').textContent=(d.pending_duplicates||0).toLocaleString();let max=Math.max(1,...d.coverage.map(x=>x.companies));document.getElementById('coverage').innerHTML=d.coverage.length?d.coverage.map(x=>`<div class="state-row"><b>${esc(x.state||'—')}</b><div class="bar"><i style="width:${Math.max(3,x.companies/max*100)}%"></i></div><span>${x.companies} firms</span><span>${x.officers} LOs</span></div>`).join(''):'<div class="empty">No warehouse coverage yet.</div>';document.getElementById('jobs').innerHTML=d.recent_jobs.length?`<table><thead><tr><th>Job</th><th>State</th><th>Status</th><th>Received</th><th>Created</th><th>Updated</th><th>Rejected</th></tr></thead><tbody>${d.recent_jobs.map(x=>`<tr><td>#${x.id}</td><td>${esc(x.state||'All')}</td><td><span class="pill">${esc(x.status)}</span></td><td>${x.records_received}</td><td>${x.companies_created}</td><td>${x.companies_updated}</td><td>${x.rejected_records}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No import jobs yet.</div>'}catch(e){fail(e)}}
async function runSearch(){try{let q=document.getElementById('q').value,state=document.getElementById('state').value.toUpperCase();let d=await api('/api/platform/warehouse/search?q='+encodeURIComponent(q)+'&state='+encodeURIComponent(state));let rows=[...d.companies.map(x=>({type:'Company',name:x.legal_name,nmls:x.nmls_id,location:[x.city,x.state].filter(Boolean).join(', '),contact:x.public_email||x.phone||'',status:x.verification_status})),...d.officers.map(x=>({type:'Loan officer',name:x.full_name,nmls:x.nmls_id,location:[x.city,x.state].filter(Boolean).join(', '),contact:x.public_email||x.phone||'',status:x.company}))];document.getElementById('results').innerHTML=rows.length?`<table><thead><tr><th>Type</th><th>Name</th><th>NMLS</th><th>Location</th><th>Public contact</th><th>Status / company</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.type)}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.nmls||'—')}</td><td>${esc(x.location||'—')}</td><td>${esc(x.contact||'—')}</td><td>${esc(x.status||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No matching warehouse records.</div>'}catch(e){fail(e)}}
document.getElementById('q').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});document.getElementById('state').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});loadOperations();loadWarehouse();
</script></body></html>'''


def _is_platform_owner():
    for user in (getattr(g, "saas_user", None), getattr(g, "current_user", None), getattr(g, "user", None)):
        if user is None:
            continue
        try:
            if bool(user["is_platform_owner"]):
                return True
        except (KeyError, TypeError):
            if bool(getattr(user, "is_platform_owner", 0)):
                return True
    return bool(session.get("is_platform_owner"))


def install_national_data_center(app):
    bp = Blueprint("national_data_center", __name__)

    @bp.get("/platform/control-tower")
    def control_tower_page():
        if not _is_platform_owner():
            return jsonify(error="Platform owner access required"), 403
        return render_template_string(PAGE)

    @bp.get("/platform/data-center")
    def legacy_data_center_page():
        return redirect("/platform/control-tower", code=302)

    app.register_blueprint(bp)
    return bp
